services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    labels:
      - homepage.group=Backup
      - homepage.name=duplicati
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
    volumes:
      - /mnt/usb:/backups
      - ${DOCKER_APPDATA}:/source
      - ${DOCKER_APPDATA}/duplicati:/config
    networks:
      - homelab
    ports:
      - 8200:8200

networks:
  homelab:
    external: true
