services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=nginx
      - homepage.href=https://nginx.${PERSONAL_DOMAIN}
      - homepage.icon=nginx-proxy-manager.svg
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/nginx/data:/data
      - ${DOCKER_APPDATA}/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
      - portainer_network
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 81:81

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=adguardhome
      - homepage.href=http://192.168.0.108:8181
      - homepage.icon=adguard-home.svg
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/adguardhome/conf:/opt/adguardhome/conf
      - ${DOCKER_APPDATA}/adguardhome/work:/opt/adguardhome/work
    networks:
      - homelab
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8181:80/tcp # Web UI

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=duckdns
      - homepage.icon=duckdns.svg
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4
    volumes:
      - ${DOCKER_APPDATA}/duckdns:/config
    network_mode: host

networks:
  homelab:
    external: true
  portainer_network:
    external: true
