services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/nginx/data:/data
      - ${DOCKER_APPDATA}/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 81:81

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/adguardhome/conf:/opt/adguardhome/conf
      - ${DOCKER_APPDATA}/adguardhome/work:/opt/adguardhome/work
    networks:
      - homelab
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8181:80/tcp # Web UI

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    user: 1000:1000
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${MY_DOMAINS}
      - PROXIED=true
    network_mode: host

networks:
  homelab:
    external: true
