services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=plex
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    devices:
      - /dev/dri:/dev/dri # Hardware transcoding device
    volumes:
      - ${DOCKER_APPDATA}/plex:/config
      - ${ROOT}/data/media:/data/media
    network_mode: host
