services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/nginx/data:/data
      - ${DOCKER_APPDATA}/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
      - portainer_network
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 81:81

networks:
  homelab:
    external: true
  portainer_network:
    external: true
